import boto3
import json

# Prompt data to be sent to the model
prompt_data = """
Write a one-liner 90s style B-movie horror/comedy pitch about a giant man-eating Python, with a hilarious and surprising twist.
"""

# Initialize the AWS Bedrock client
bedrock = boto3.client(service_name="bedrock-runtime")

# Define the payload with the prompt and model parameters
payload = {
    "prompt": f"\n\nHuman: {prompt_data}\n\nAssistant:",
    "max_tokens_to_sample": 512,
    "temperature": 0.8,
    "top_p": 0.8,
}

# Convert the payload to JSON
body = json.dumps(payload)

# Specify the model to be used (Anthropic's Claude model)
model_id = "anthropic.claude-v2"

# Invoke the model with the Bedrock client
response = bedrock.invoke_model(
    body=body,
    modelId=model_id,
    accept="application/json",
    contentType="application/json",
)

# Parse the response body from the model invocation
response_body = json.loads(response.get("body").read())

# Extract the completion (text generated by the model)
response_text = response_body.get("completion")

# Print the response text
print(response_text)
